//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportWebAPIExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hierarchy
    {
        public decimal Id { get; set; }
        public Nullable<decimal> OrganizationId { get; set; }
        public string UnitType { get; set; }
        public Nullable<decimal> ParentHierarchyId { get; set; }
        public string HierarchyName { get; set; }
        public Nullable<decimal> ObjectNumber { get; set; }
        public Nullable<decimal> HierarchyId { get; set; }
    }
}
