//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportWebAPIExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemDefinition
    {
        public Nullable<decimal> Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public Nullable<decimal> SLUSort { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public string DefinitionOptionBits { get; set; }
        public Nullable<decimal> SpecialCount { get; set; }
        public Nullable<decimal> Icon { get; set; }
        public Nullable<decimal> Tare { get; set; }
        public Nullable<decimal> PrepTime { get; set; }
        public Nullable<decimal> NLU { get; set; }
        public Nullable<bool> MoveFlag { get; set; }
        public Nullable<decimal> NLUGroup { get; set; }
        public Nullable<decimal> SLU { get; set; }
        public Nullable<decimal> MobileSLU { get; set; }
        public string MainMenuLevel { get; set; }
        public string SubMenuLevel { get; set; }
        public Nullable<decimal> PrefixLevelOverride { get; set; }
        public Nullable<decimal> PrintClassOverride { get; set; }
        public Nullable<decimal> MenuItemClass { get; set; }
        public string LongDescriptor { get; set; }
        public decimal HierarchyId { get; set; }
        public decimal DefinitionSequence { get; set; }
        public decimal MenuItemMasterId { get; set; }
    }
}
