//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportWebAPIExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemClass
    {
        public Nullable<decimal> Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> TaxClass { get; set; }
        public string OptionBits { get; set; }
        public string MainMenuLevel { get; set; }
        public string SubMenuLevel { get; set; }
        public string PrintingOptionBits { get; set; }
        public Nullable<decimal> PrintGroup { get; set; }
        public Nullable<decimal> PrivilegeGroup { get; set; }
        public Nullable<decimal> SalesItemizer { get; set; }
        public Nullable<decimal> DiscountItemizer { get; set; }
        public Nullable<decimal> ServiceChargeItemizer { get; set; }
        public Nullable<decimal> HighAmountLockout { get; set; }
        public Nullable<bool> MainLevelDefault { get; set; }
        public Nullable<bool> SubLevelDefault { get; set; }
        public Nullable<decimal> CondimentOrderType { get; set; }
        public Nullable<decimal> DefaultMasterGroup { get; set; }
        public Nullable<decimal> CountEntry { get; set; }
        public Nullable<decimal> CountDisplay { get; set; }
        public Nullable<decimal> PricingCalculator { get; set; }
        public Nullable<decimal> KDSOrDiningCourse { get; set; }
        public Nullable<decimal> PrintClass { get; set; }
        public string NextPanel { get; set; }
        public Nullable<decimal> NextPage { get; set; }
        public Nullable<decimal> CondimentPrefixType { get; set; }
        public Nullable<decimal> KdsHighlightScheme { get; set; }
        public Nullable<decimal> MaximumRefillCount { get; set; }
        public string RefillDescriptor { get; set; }
        public Nullable<decimal> CondimentOrderPopup { get; set; }
        public Nullable<decimal> CondimentEditPopup { get; set; }
        public Nullable<decimal> ServiceChargeGroup { get; set; }
        public string MemberOfCondiments { get; set; }
        public string RequiredCondiments { get; set; }
        public string AllowedCondiments { get; set; }
        public decimal ObjectNumber { get; set; }
        public decimal HierarchyId { get; set; }
    }
}
