//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportWebAPIExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemPrice
    {
        public Nullable<decimal> Id { get; set; }
        public string PriceOptionBits { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PrepCost { get; set; }
        public Nullable<decimal> MenuLevel { get; set; }
        public Nullable<decimal> TaxClass { get; set; }
        public Nullable<decimal> EffectivityGroup { get; set; }
        public Nullable<decimal> ServiceChargeGroup { get; set; }
        public decimal HierarchyId { get; set; }
        public decimal PriceSequence { get; set; }
        public decimal MenuItemDefID { get; set; }
    }
}
