//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportExportWebAPIExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemMaster
    {
        public Nullable<decimal> Id { get; set; }
        public Nullable<decimal> MasterName { get; set; }
        public Nullable<decimal> ReportGroup { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> MajorGroup { get; set; }
        public Nullable<decimal> FamilyGroup { get; set; }
        public Nullable<decimal> RecipeLink { get; set; }
        public string MenuItemName { get; set; }
        public decimal ObjectNumber { get; set; }
        public decimal HierarchyId { get; set; }
    }
}
